### ISSUE TITLE
Group Algorithms and Data Structures

### ISSUE THREAD

**Issue by pongtaewin** [Phon1209/Competitive_algorithm_and_data_structures#5]
Maybe grouping will do better in finding these code, when needed?

**Comment by Phon1209** [comment]
What do you mean by “grouping”

**Comment by pongtaewin** [comment]
Group in relevant ds/algo type, for easier usage.
it's like #include <cpds/tree/avl.h> maybe?

**Comment by Phon1209** [comment]
Thank you for your suggestion.
I will fix it in no time.
